Maistra 1.0
Maistra/rpms pull request #55
Opened 2019-07-23 21:47 UTC by brian-avery

2019-07-23 22:10 UTC, jwendell reviewed
LGTM, just 2 trivial changes

2019-07-23 22:10 UTC, jwendell commented on istio-proxy/update.sh
> +}
nit: indentation of this line is different than others

2019-07-23 22:10 UTC, jwendell commented on istio-proxy/update.sh
> +	local tar_name=istio-proxy.${1}.tar.xz
do you want to use `${proxy_sha}` instead of `${1}`?

2019-07-23 22:14 UTC, dmitri-d approved these changes

2019-07-23 22:35 UTC, jwendell approved these changes

2019-07-23 22:49 UTC, bdecoste commented
lgtm

2019-07-23 22:49 UTC, bdecoste approved these changes
lgtm

2019-07-23 23:39 UTC, knrc requested changes
The fetch.sh script is not deterministic so we cannot use the SHA, until this is fixed this must remain checksum

2019-07-24 00:00 UTC, bdecoste commented
Kev is right and even if fetch is deterministic the resulting tarball will not be because we don't know which fetch version was run or which params were passed into fetch. I have opened a jira to make fetch itself deterministic: https://issues.jboss.org/browse/MAISTRA-687

2019-07-24 12:11 UTC, knrc approved these changes

2019-07-24 12:12 UTC, merged