MAISTRA-1281: Print version and SHA in the output of --version
Maistra/rpms pull request #89
Opened 2020-03-18 18:33 UTC by jwendell

Before:
```
envoy  version: 1584322855/1.12.0/Maistra/...
```

After:
```
envoy  version: e885dd6880407edd27c81f8f42c5480a6d80751d/1.12.0/Maistra 1.1.0-1.el8/...
```

We don't need to perform this operation beforehand (fetch phase), we can take
the same approach as Istio package and run this at RPM build phase.

2020-03-18 18:35 UTC, jwendell commented
BTW, in _before_ output above that number is the output of `date +%s` which means nothing.

2020-03-18 18:41 UTC, brian-avery commented on istio-proxy/istio-proxy.spec
> +sed -e "s/@REVISION@/%{proxy_git_commit}/" -e "s/@VERSION@/%{version}-%{release}/" %{SOURCE5} > proxy/tools/bazel_get_workspace_status
The version stuff will be nice :)

2020-03-18 18:44 UTC, knrc requested changes
This was supposed to be post-1.1 so I'm blocking for now

2020-05-27 18:48 UTC, jwendell commented
Closing in favor of https://github.com/Maistra/rpms/pull/98

2020-05-27 18:48 UTC, closed without merging